config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/help'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  ##############################################################################
  # Set locale according to the selected value in a View (see ApplicationHelper)
  #
  # 17.11.2013
  # 27.11.2013  Last update ('es' added)
  ##############################################################################
  def set_locale
    if    params[:locale] == "ru"
      I18n.locale = :ru
    elsif params[:locale] == "es"
      I18n.locale = :es
    else
      I18n.locale = :en
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @page_title ='Home'
  end

  def help
    # title to be set via provide method in the View
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  ##############################################################################
  # Get Application name (used by page_title)
  #   Alternatives:
  #       Rails.application.class.to_s.split("::").first
  #       Rails.application.config.session_options[:key].sub(/^_/,'').sub(/_session/,'')
  #       Rails.application.engine_name.gsub(/_application/,'')
  #
  # 15.12.2013  Created
  ##############################################################################
  def app_name
    Rails.application.class.parent_name
  end

  ##############################################################################
  # Handles Error messages with Bootstrap 3 styles
  # Source: http://stackoverflow.com/questions/15155890/styling-form-error-message-bootstrap-rails
  #
  # 18.07.2015 ZT
  ##############################################################################
  def errors_for(object)
    if object.errors.any?
      content_tag(:div, :class => "panel panel-danger") do
        concat(content_tag(:div, :class => "panel-heading") do
          concat(content_tag(:h4, :class => "panel-title") do
            concat "Объект '#{t(object.class.name.camelcase.underscore)}' не может быть сохранен из-за ошибок:"
          end)
        end)
        concat(content_tag(:div, :class => "panel-body") do
          concat(content_tag(:ul) do
            object.errors.full_messages.each do |msg|
                concat content_tag(:li, msg)
            end
          end)
        end)
      end
    end
  end
end

  ##############################################################################
  # HTML element to switch language among available ones
  #
  # Source:  http://dhampik.ru/blog/rails-routes-tricks-with-locales
  #
  # 17.11.2013  The `alternative version` in the source is used
  ##############################################################################
  def language_switch
    content_tag(:ul, id: 'switch') do
      I18n.available_locales.each do |loc|
        locale_param = request.path == root_path ? root_path(locale: loc) : params.merge(locale: loc)
        concat content_tag(:li, (link_to I18n.t(:language, locale: loc), locale_param), class: (I18n.locale == loc ? "active" : ""))
      end
    end
  end

  ##############################################################################
  # Return a title on a per-page basis with localization
  # Source:  Michael Hartl (Chapter 4, Listing 4.2)
  #
  # 15.12.2013  Created
  # 29.09.2015  Last update
  ##############################################################################
  def page_title(provided_title = '')
    if provided_title.empty?
      if controller_name == 'pages'
#       title = @page_title || ("#{t action_name.capitalize}")
        title = @page_title || ("#{action_name.capitalize}")
      else
#       title = @page_title || "#{t controller_name.capitalize}-#{t action_name.capitalize}"
        title = @page_title || "#{controller_name.capitalize}-#{action_name.capitalize}"
      end
    else
      title = provided_title    # Title is set via provide method in a View
    end
    "#{app_name} | #{title}"
  end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_debug.html.haml
%p
  Версии:
  %br
    = "#{RUBY_ENGINE}-#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL} | Rails: #{Rails.version}"
    %br
    - if Rails.env.development?
      = "Git Branch: #{GIT_BRANCH}; Commit: #{GIT_COMMIT} (#{l GIT_COMMIT_TIMESTAMP, format: '%d.%m.%Y %H:%M'})"

app/views/layouts/_footer.html.haml
%footer
  &copy; 2015 ZT Lab
  %br
  = render 'layouts/debug' if Rails.env.development?

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to image_tag('site/logo.jpg', alt: "Go to Home page", title: 'To Home'), root_path
    /%h1 Documents Collection
    /%h2 Managed by Egor Kozlov

    %nav
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Home",   root_path
        %li= link_to "Help",   pages_help_path
        %li= link_to "Log in", '#'

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= page_title(yield(:title))
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = render 'layouts/shim'

  %body
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'

app/views/pages/help.html.haml
- provide :title,  'Help'
.center.jumbotron
  %h1 Help
  %p To be developed

app/views/pages/home.html.haml
/- provide :title,  'Home'
.center.jumbotron
  %h2 Documents Collection
  %h4 Managed by Egor Kozlov

#logo= link_to image_tag('site/logo.jpg', alt: "Go to Home page", title: 'To Home')#, root_path